services:
  _defaults:
    public: false
    autowire: false
    autoconfigure: false

  Wedding\Port\MessageBus\CommandBusInterface: '@Wedding\Infrastructure\MessageBus\Symfony\CommandBus'
  Wedding\Port\MessageBus\QueryBusInterface: '@Wedding\Infrastructure\MessageBus\Symfony\QueryBus'
