doctrine_migrations:
    migrations_paths:
      Wedding\Infrastructure\Persistence\Doctrine\Migrations: '%kernel.project_dir%/src/Wedding/Infrastructure/Persistence/Doctrine/Migrations'
    all_or_nothing: true
