framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        name: 'wedding_session'
        cookie_lifetime: 3600
        handler_id: null
        cookie_path: /invite
        cookie_samesite: strict

    translator:
      enabled_locales: ['en']

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
      base_path: '/assets'
