security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: null }
        invites:
          id: Wedding\Infrastructure\Auth\Symfony\Security\User\InviteUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        invites:
          pattern: ^/invite
          anonymous: false
          lazy: true
          logout:
            path: invite_logout
          security: true
          methods: ['POST', 'GET']
          provider: invites
          guard:
            authenticators:
              - Wedding\Infrastructure\Auth\Symfony\Security\Guard\InviteCodeAuthenticator
        public:
          pattern: ^/
          security: false

    access_control:
         - { path: ^/invite/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/invite/login-form, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/invite/, roles: ROLE_RSVP_INVITE }
