parameters:

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: false

    Wedding\Application\Http\Action\Web\:
        resource: '%kernel.project_dir%/src/Wedding/Application/Http/Action/Web'
        public: true

    Wedding\Application\Console\:
      resource: '%kernel.project_dir%/src/Wedding/Application/Console'
      tags:
        - { name: 'console.command' }

    Wedding\Infrastructure\:
      resource: '%kernel.project_dir%/src/Wedding/Infrastructure/'

    domain_command_handlers:
      namespace: Wedding\Domain\Command\
      resource: '%kernel.project_dir%/src/Wedding/Domain/Command/*Handler.php'
      tags:
        - { name: messenger.message_handler, bus: command.bus }
