parameters:

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: false

    Wedding\Application\Http\Action\Web\:
        resource: '../src/Wedding/Application/Http/Action/Web'
        public: true
