version: '3.5'

services:
  php:
    image: 'wedding-website:dev'
    build:
      context: .
      dockerfile: ./infrastructure/php/Dockerfile
      target: dev
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - './:/srv/app/:cached'
      - /srv/app/vendor
      - /srv/app/var
      # to allow composer to function inside the container
      - ~/.ssh:/root/.ssh:ro
      - ~/.ssh:/var/www/.ssh:ro
      - ~/.composer:/var/www/.composer
