version: '2.4'

services:
  php:
    image: 'gsdevme/wedding-website:ci'
    build:
      context: .
      dockerfile: ./infrastructure/php/Dockerfile
      target: ci
    environment:
      - APP_ENV=dev
    volumes: [ ]
